
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shippingservice
  description: This service is responsible to process a checkout order from the user. The checkout service will call many other services in order to process an order.
  annotations:
    backstage.io/techdocs-ref: url:https://raw.githubusercontent.com/open-telemetry/opentelemetry.io/main/content/en/docs/demo/services/shipping.md
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
  dependsOn:
    - component:default/featureflagservice
    - component:default/quoteservice
