{
 "title": "Opentelemetry Collector Data Flow",
 "description": "otelcol metrics dashboard",
 "tags": [
  "opentelemetry",
  "opentelemetry collector",
  "otelcol"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_version",
    "label": "service_version",
    "query": {
     "query": "query_result(sum(otelcol_process_uptime{}) by (service_version))\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Otel Collector Instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(otelcol_process_cpu_seconds{service_instance_id=~\".*\"}) by (service_instance_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "gauge",
   "description": "otelcol_process_cpu_seconds",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(otelcol_process_cpu_seconds{}[$__rate_interval])*100) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Rss",
   "type": "gauge",
   "description": "avg(otelcol_process_memory_rss{}) by (instance)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(otelcol_process_memory_rss{}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 10, "x": 9, "y": 1 },
   "options": {
    "content": "# Opentelemetry Collector Data Flow\n\nopentelemetry collector contrib Data Ingress/Egress metrics are in focus.\n\n`service_version:` ${service_version}\n\n"
   }
  },
  {
   "type": "text",
   "description": "Sent by Exporter",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": {
    "content": "\n \n## Prometheus Config\n\n`evaluation_interval:` 30s\n\n`scrape_interval:` 5s"
   }
  },
  {
   "title": "TracingPipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Export Ratio",
     "type": "gauge",
     "gridPos": { "h": 24, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(avg(sum by(job) (rate(otelcol_exporter_sent_spans{}[$__range])))/avg(sum by(job) (rate(otelcol_receiver_accepted_spans{}[$__range]))) ) * 50",
       "legendFormat": "%{{job}}"
      }
     ]
    },
    {
     "title": "Acceptted v.s Export",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "avg(sum by()  (rate(otelcol_receiver_accepted_spans{}[$__rate_interval]))) ",
       "legendFormat": "accepted"
      },
      {
       "expr": "(avg( sum by() (rate(otelcol_exporter_sent_spans{}[$__rate_interval]))\n))",
       "legendFormat": "export"
      }
     ]
    },
    {
     "title": "Trace Signalling Pipelines",
     "type": "nodeGraph",
     "gridPos": { "h": 11, "w": 21, "x": 3, "y": 11 },
     "targets": [
      {
       "expr": "label_join(label_join(\n(rate(otelcol_receiver_accepted_spans{}[$__interval]))\n, \"id\", \"\", \"transport\", \"receiver\")\n, \"title\", \"\", \"transport\", \"receiver\")\n\nor\n\nlabel_replace(label_replace(\nsum by(service_name) (rate(otelcol_receiver_accepted_spans{}[$__interval]))\n, \"id\", \"processor\", \"dummynode\", \"\")\n, \"title\", \"processor\", \"dummynode\", \"\")\n\nor\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n, \"id\", \"$0\", \"processor\", \".*\")\n, \"title\", \"$0\", \"processor\", \".*\")\n\nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_spans{}[$__interval]))\n, \"id\", \"exporter\", \"dummynode\", \"\")\n, \"title\", \"exporter\", \"dummynode\", \"\")\n        \nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_spans{}[$__interval]))\n, \"id\", \"$0\", \"exporter\", \".*\")\n, \"title\", \"$0\", \"exporter\", \".*\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\nlabel_replace(label_join(\n(rate(otelcol_receiver_accepted_spans{}[$__interval]))\n\n ,\"source\",\"\",\"transport\",\"receiver\")\n,\"target\",\"processor\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\n  or\n\n  label_join(\nlabel_replace(label_replace(\n  (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n ,\"source\",\"processor\",\"\",\"\")\n,\"target\",\"$0\",\"processor\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\n  label_join(\nlabel_replace(label_replace(\n    (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n ,\"source\",\"$0\",\"processor\",\".*\")\n,\"target\",\"exporter\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\n  label_join(\nlabel_replace(label_replace(\n   (rate(otelcol_exporter_sent_spans{}[$__interval]))\n ,\"source\",\"exporter\",\"\",\"\")\n,\"target\",\"$0\",\"exporter\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Accepted",
     "type": "stat",
     "description": "Spans Accepted by Receiver and Transport",
     "gridPos": { "h": 5, "w": 5, "x": 3, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_accepted_spans{}[$__rate_interval])) by (receiver,transport)",
       "legendFormat": "{{receiver}}-{{transport}}"
      }
     ]
    },
    {
     "title": "Total Accepted ",
     "type": "gauge",
     "description": "Total Spans Accepted ",
     "gridPos": { "h": 5, "w": 3, "x": 8, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_accepted_spans{}[$__rate_interval])) ",
       "legendFormat": "{{receiver}}-{{transport}}"
      }
     ]
    },
    {
     "title": "Batch",
     "type": "stat",
     "description": "Total Batch Processed",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum{}[$__rate_interval]))  by (processor)",
       "legendFormat": "{{processor}}"
      }
     ]
    },
    {
     "title": "Total Export ",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 16, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_sent_spans{}[$__interval])) ",
       "legendFormat": "{{processor}}"
      }
     ]
    },
    {
     "title": "Sent",
     "type": "stat",
     "description": "Sent by Exporter",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_sent_spans{}[$__rate_interval])) by (exporter)",
       "legendFormat": "{{processor}}"
      }
     ]
    },
    {
     "title": "Refused",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 3, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_refused_spans{}[$__rate_interval])) by (receiver,transport)",
       "legendFormat": "{{receiver}}-{{transport}}"
      }
     ]
    },
    {
     "title": "Total Refused ",
     "type": "gauge",
     "description": "Total Spans Accepted ",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_refused_spans{}[$__rate_interval])) ",
       "legendFormat": "{{receiver}}-{{transport}}"
      }
     ]
    },
    {
     "title": "Total Failed Export ",
     "type": "gauge",
     "description": "otelcol_exporter_send_failed_spans",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_send_failed_spans{}[$__rate_interval])) ",
       "legendFormat": "{{processor}}"
      }
     ]
    },
    {
     "title": "Failed",
     "type": "stat",
     "description": "Sent by Exporter\notelcol_exporter_send_failed_spans",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_send_failed_spans{}[$__rate_interval])) by (exporter)",
       "legendFormat": "{{processor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics Pipeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric Export Ratio",
     "type": "gauge",
     "gridPos": { "h": 25, "w": 3, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(avg(sum by(job) (rate(otelcol_exporter_sent_metric_points{}[$__range])))/avg(sum by(job) (rate(otelcol_receiver_accepted_metric_points{}[$__range]))) )*50",
       "legendFormat": "%{{job}}"
      }
     ]
    },
    {
     "title": "Acceptted v.s Export",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "avg(sum (rate(otelcol_receiver_accepted_metric_points{}[5m]))) ",
       "legendFormat": "accepted"
      },
      {
       "expr": "avg(sum(rate(otelcol_exporter_sent_metric_points{}[5m])) )",
       "legendFormat": "export"
      }
     ]
    },
    {
     "title": "Metrics Signalling Pipelines",
     "type": "nodeGraph",
     "gridPos": { "h": 11, "w": 21, "x": 3, "y": 12 },
     "targets": [
      {
       "expr": "\nlabel_join(label_join(\n(rate(otelcol_receiver_accepted_metric_points{}[$__interval]))\n, \"id\", \"\", \"transport\", \"receiver\")\n, \"title\", \"\", \"transport\", \"receiver\")\n\nor\n\nlabel_replace(label_replace(\nsum by(service_name) (rate(otelcol_receiver_accepted_spans{}[$__interval]))\n, \"id\", \"processor\", \"dummynode\", \"\")\n, \"title\", \"processor\", \"dummynode\", \"\")\n\n\n\nor\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n, \"id\", \"$0\", \"processor\", \".*\")\n, \"title\", \"$0\", \"processor\", \".*\")\n\n\n\n\n\nor\nlabel_replace(label_replace(\nsum (rate(otelcol_exporter_sent_metric_points{}[$__interval]))\n, \"id\", \"exporter\", \"dummynode\", \"\")\n, \"title\", \"exporter\", \"dummynode\", \"\")\n\nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_metric_points{}[$__interval]))\n, \"id\", \"$0\", \"exporter\", \".*\")\n, \"title\", \"$0\", \"exporter\", \".*\")",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\nlabel_replace(label_join(\n(rate(otelcol_receiver_accepted_metric_points{}[$__interval]))\n\n,\"source\",\"\",\"transport\",\"receiver\")\n,\"target\",\"processor\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\n\nor\n\nlabel_join(\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n,\"source\",\"processor\",\"\",\"\")\n,\"target\",\"$0\",\"processor\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\n\n\n\n\nor\n\n\nlabel_join(\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n,\"source\",\"$0\",\"processor\",\".*\")\n,\"target\",\"exporter\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\nlabel_join(\nlabel_replace(label_replace(\n(rate(otelcol_exporter_sent_metric_points{}[$__interval]))\n,\"source\",\"exporter\",\"\",\"\")\n,\"target\",\"$0\",\"exporter\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Accepted",
     "type": "stat",
     "description": "otelcol_receiver_accepted_metric_points",
     "gridPos": { "h": 6, "w": 5, "x": 3, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_accepted_metric_points{}[$__rate_interval])) by (receiver,transport)",
       "legendFormat": "{{receiver}}-{{transport}}"
      }
     ]
    },
    {
     "title": "Total Accepted ",
     "type": "gauge",
     "description": "otelcol_receiver_accepted_metric_points",
     "gridPos": { "h": 6, "w": 3, "x": 8, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_accepted_metric_points{}[$__rate_interval])) ",
       "legendFormat": "{{receiver}}-{{transport}}"
      }
     ]
    },
    {
     "title": "Batch",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum{}[$__rate_interval]))  by (processor)",
       "legendFormat": "{{processor}}"
      }
     ]
    },
    {
     "title": "Total Export ",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 16, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_sent_metric_points{}[$__rate_interval])) ",
       "legendFormat": "{{processor}}"
      }
     ]
    },
    {
     "title": "Sent",
     "type": "stat",
     "description": "Sent by Exporter",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_sent_metric_points{}[$__rate_interval])) by (exporter) ",
       "legendFormat": "{{processor}}"
      }
     ]
    },
    {
     "title": "Refused",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 3, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_refused_metric_points{}[$__rate_interval])) by (receiver,transport)",
       "legendFormat": "{{receiver}}-{{transport}}"
      }
     ]
    },
    {
     "title": "Total Refused ",
     "type": "gauge",
     "description": "Total Spans Accepted ",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_receiver_refused_metric_points{}[$__rate_interval])) ",
       "legendFormat": "{{receiver}}-{{transport}}"
      }
     ]
    },
    {
     "title": "Total Failed Export ",
     "type": "gauge",
     "description": "otelcol_exporter_send_failed_spans",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_send_failed_metric_points{}[$__rate_interval])) ",
       "legendFormat": "{{processor}}"
      }
     ]
    },
    {
     "title": "Failed",
     "type": "stat",
     "description": "Sent by Exporter\notelcol_exporter_send_failed_spans",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_exporter_send_failed_metric_points{}[$__rate_interval])) by (exporter)",
       "legendFormat": "{{processor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus Scrape Figures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Exporter vs. Scraped",
     "type": "gauge",
     "description": "otelcol prometheus exporter 9464 export rate versus prometheus scrape metrics",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum_over_time(scrape_samples_scraped{job=\"otel\"}[$__range])/ count_over_time(scrape_samples_scraped{job=\"otel\"}[$__range])/(5*30)) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum(rate(otelcol_exporter_sent_metric_points{exporter=\"prometheus\"}[$__rate_interval])) )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Samples Scraped",
     "type": "stat",
     "description": "sum_over_time(scrape_samples_scraped[$__range])/ count_over_time(scrape_samples_scraped[$__range])",
     "gridPos": { "h": 9, "w": 5, "x": 3, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time(scrape_samples_scraped[$__range])/ count_over_time(scrape_samples_scraped[$__range])/(5*30)",
       "legendFormat": "{{job}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Prometheus Scrape",
     "type": "nodeGraph",
     "gridPos": { "h": 9, "w": 11, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_replace(\nsum (scrape_samples_scraped{job!=\"\"}) by (instance)\n, \"id\", \"$0\", \"instance\", \".*\")\n, \"title\", \"$0\", \"instance\", \".*\")\n,\"mainstat\",\"\",\"\",\"\")\n\nor \n\nlabel_replace(label_replace(label_replace(\nsum (scrape_samples_scraped{job!=\"\"})\n, \"id\", \"prometheus\", \"\", \"\")\n, \"title\", \"prometheus\", \"\", \"\")\n,\"mainstat\",\"\",\"\",\"\")\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_join(\nlabel_replace(label_replace(\nsum (scrape_samples_scraped{job!=\"\"}) by (instance)\n,\"source\",\"$0\",\"instance\",\".*\")\n,\"target\",\"prometheus\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Samples Scraped",
     "type": "gauge",
     "description": "scrape_samples_scraped{job!=\"\"}",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time(scrape_samples_scraped[$__range])/ count_over_time(scrape_samples_scraped[$__range])/(5*30)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}