# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

file_format: definition/2
attribute_groups:
  - id: service.product_reviews
    visibility: public
    brief: Product Reviews service attributes
    stability: stable
    attributes:
      - ref: demo.product.id
      - ref: demo.product.review.count
      - ref: demo.product.review.average_score
      - ref: demo.product.review.question
