// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package oteldemo;

public final class Demo {
  private Demo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AdRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:oteldemo.AdRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * List of important key words from the current page describing the context.
     * </pre>
     *
     * <code>repeated string context_keys = 1;</code>
     * @return A list containing the contextKeys.
     */
    java.util.List<java.lang.String>
        getContextKeysList();
    /**
     * <pre>
     * List of important key words from the current page describing the context.
     * </pre>
     *
     * <code>repeated string context_keys = 1;</code>
     * @return The count of contextKeys.
     */
    int getContextKeysCount();
    /**
     * <pre>
     * List of important key words from the current page describing the context.
     * </pre>
     *
     * <code>repeated string context_keys = 1;</code>
     * @param index The index of the element to return.
     * @return The contextKeys at the given index.
     */
    java.lang.String getContextKeys(int index);
    /**
     * <pre>
     * List of important key words from the current page describing the context.
     * </pre>
     *
     * <code>repeated string context_keys = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the contextKeys at the given index.
     */
    com.google.protobuf.ByteString
        getContextKeysBytes(int index);
  }
  /**
   * Protobuf type {@code oteldemo.AdRequest}
   */
  public static final class AdRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:oteldemo.AdRequest)
      AdRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdRequest.newBuilder() to construct.
    private AdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdRequest() {
      contextKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AdRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                contextKeys_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              contextKeys_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          contextKeys_ = contextKeys_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return oteldemo.Demo.internal_static_oteldemo_AdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return oteldemo.Demo.internal_static_oteldemo_AdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              oteldemo.Demo.AdRequest.class, oteldemo.Demo.AdRequest.Builder.class);
    }

    public static final int CONTEXT_KEYS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList contextKeys_;
    /**
     * <pre>
     * List of important key words from the current page describing the context.
     * </pre>
     *
     * <code>repeated string context_keys = 1;</code>
     * @return A list containing the contextKeys.
     */
    public com.google.protobuf.ProtocolStringList
        getContextKeysList() {
      return contextKeys_;
    }
    /**
     * <pre>
     * List of important key words from the current page describing the context.
     * </pre>
     *
     * <code>repeated string context_keys = 1;</code>
     * @return The count of contextKeys.
     */
    public int getContextKeysCount() {
      return contextKeys_.size();
    }
    /**
     * <pre>
     * List of important key words from the current page describing the context.
     * </pre>
     *
     * <code>repeated string context_keys = 1;</code>
     * @param index The index of the element to return.
     * @return The contextKeys at the given index.
     */
    public java.lang.String getContextKeys(int index) {
      return contextKeys_.get(index);
    }
    /**
     * <pre>
     * List of important key words from the current page describing the context.
     * </pre>
     *
     * <code>repeated string context_keys = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the contextKeys at the given index.
     */
    public com.google.protobuf.ByteString
        getContextKeysBytes(int index) {
      return contextKeys_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < contextKeys_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contextKeys_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < contextKeys_.size(); i++) {
          dataSize += computeStringSizeNoTag(contextKeys_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getContextKeysList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof oteldemo.Demo.AdRequest)) {
        return super.equals(obj);
      }
      oteldemo.Demo.AdRequest other = (oteldemo.Demo.AdRequest) obj;

      if (!getContextKeysList()
          .equals(other.getContextKeysList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContextKeysCount() > 0) {
        hash = (37 * hash) + CONTEXT_KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getContextKeysList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static oteldemo.Demo.AdRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oteldemo.Demo.AdRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oteldemo.Demo.AdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oteldemo.Demo.AdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oteldemo.Demo.AdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oteldemo.Demo.AdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oteldemo.Demo.AdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static oteldemo.Demo.AdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static oteldemo.Demo.AdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static oteldemo.Demo.AdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static oteldemo.Demo.AdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static oteldemo.Demo.AdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(oteldemo.Demo.AdRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code oteldemo.AdRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:oteldemo.AdRequest)
        oteldemo.Demo.AdRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return oteldemo.Demo.internal_static_oteldemo_AdRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return oteldemo.Demo.internal_static_oteldemo_AdRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                oteldemo.Demo.AdRequest.class, oteldemo.Demo.AdRequest.Builder.class);
      }

      // Construct using oteldemo.Demo.AdRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        contextKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return oteldemo.Demo.internal_static_oteldemo_AdRequest_descriptor;
      }

      @java.lang.Override
      public oteldemo.Demo.AdRequest getDefaultInstanceForType() {
        return oteldemo.Demo.AdRequest.getDefaultInstance();
      }

      @java.lang.Override
      public oteldemo.Demo.AdRequest build() {
        oteldemo.Demo.AdRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public oteldemo.Demo.AdRequest buildPartial() {
        oteldemo.Demo.AdRequest result = new oteldemo.Demo.AdRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          contextKeys_ = contextKeys_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.contextKeys_ = contextKeys_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof oteldemo.Demo.AdRequest) {
          return mergeFrom((oteldemo.Demo.AdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(oteldemo.Demo.AdRequest other) {
        if (other == oteldemo.Demo.AdRequest.getDefaultInstance()) return this;
        if (!other.contextKeys_.isEmpty()) {
          if (contextKeys_.isEmpty()) {
            contextKeys_ = other.contextKeys_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureContextKeysIsMutable();
            contextKeys_.addAll(other.contextKeys_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        oteldemo.Demo.AdRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (oteldemo.Demo.AdRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList contextKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureContextKeysIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          contextKeys_ = new com.google.protobuf.LazyStringArrayList(contextKeys_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * List of important key words from the current page describing the context.
       * </pre>
       *
       * <code>repeated string context_keys = 1;</code>
       * @return A list containing the contextKeys.
       */
      public com.google.protobuf.ProtocolStringList
          getContextKeysList() {
        return contextKeys_.getUnmodifiableView();
      }
      /**
       * <pre>
       * List of important key words from the current page describing the context.
       * </pre>
       *
       * <code>repeated string context_keys = 1;</code>
       * @return The count of contextKeys.
       */
      public int getContextKeysCount() {
        return contextKeys_.size();
      }
      /**
       * <pre>
       * List of important key words from the current page describing the context.
       * </pre>
       *
       * <code>repeated string context_keys = 1;</code>
       * @param index The index of the element to return.
       * @return The contextKeys at the given index.
       */
      public java.lang.String getContextKeys(int index) {
        return contextKeys_.get(index);
      }
      /**
       * <pre>
       * List of important key words from the current page describing the context.
       * </pre>
       *
       * <code>repeated string context_keys = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the contextKeys at the given index.
       */
      public com.google.protobuf.ByteString
          getContextKeysBytes(int index) {
        return contextKeys_.getByteString(index);
      }
      /**
       * <pre>
       * List of important key words from the current page describing the context.
       * </pre>
       *
       * <code>repeated string context_keys = 1;</code>
       * @param index The index to set the value at.
       * @param value The contextKeys to set.
       * @return This builder for chaining.
       */
      public Builder setContextKeys(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContextKeysIsMutable();
        contextKeys_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of important key words from the current page describing the context.
       * </pre>
       *
       * <code>repeated string context_keys = 1;</code>
       * @param value The contextKeys to add.
       * @return This builder for chaining.
       */
      public Builder addContextKeys(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureContextKeysIsMutable();
        contextKeys_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of important key words from the current page describing the context.
       * </pre>
       *
       * <code>repeated string context_keys = 1;</code>
       * @param values The contextKeys to add.
       * @return This builder for chaining.
       */
      public Builder addAllContextKeys(
          java.lang.Iterable<java.lang.String> values) {
        ensureContextKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, contextKeys_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of important key words from the current page describing the context.
       * </pre>
       *
       * <code>repeated string context_keys = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContextKeys() {
        contextKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * List of important key words from the current page describing the context.
       * </pre>
       *
       * <code>repeated string context_keys = 1;</code>
       * @param value The bytes of the contextKeys to add.
       * @return This builder for chaining.
       */
      public Builder addContextKeysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureContextKeysIsMutable();
        contextKeys_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:oteldemo.AdRequest)
    }

    // @@protoc_insertion_point(class_scope:oteldemo.AdRequest)
    private static final oteldemo.Demo.AdRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new oteldemo.Demo.AdRequest();
    }

    public static oteldemo.Demo.AdRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdRequest>
        PARSER = new com.google.protobuf.AbstractParser<AdRequest>() {
      @java.lang.Override
      public AdRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public oteldemo.Demo.AdRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AdResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:oteldemo.AdResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .oteldemo.Ad ads = 1;</code>
     */
    java.util.List<oteldemo.Demo.Ad> 
        getAdsList();
    /**
     * <code>repeated .oteldemo.Ad ads = 1;</code>
     */
    oteldemo.Demo.Ad getAds(int index);
    /**
     * <code>repeated .oteldemo.Ad ads = 1;</code>
     */
    int getAdsCount();
    /**
     * <code>repeated .oteldemo.Ad ads = 1;</code>
     */
    java.util.List<? extends oteldemo.Demo.AdOrBuilder> 
        getAdsOrBuilderList();
    /**
     * <code>repeated .oteldemo.Ad ads = 1;</code>
     */
    oteldemo.Demo.AdOrBuilder getAdsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code oteldemo.AdResponse}
   */
  public static final class AdResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:oteldemo.AdResponse)
      AdResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AdResponse.newBuilder() to construct.
    private AdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AdResponse() {
      ads_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AdResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AdResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                ads_ = new java.util.ArrayList<oteldemo.Demo.Ad>();
                mutable_bitField0_ |= 0x00000001;
              }
              ads_.add(
                  input.readMessage(oteldemo.Demo.Ad.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          ads_ = java.util.Collections.unmodifiableList(ads_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return oteldemo.Demo.internal_static_oteldemo_AdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return oteldemo.Demo.internal_static_oteldemo_AdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              oteldemo.Demo.AdResponse.class, oteldemo.Demo.AdResponse.Builder.class);
    }

    public static final int ADS_FIELD_NUMBER = 1;
    private java.util.List<oteldemo.Demo.Ad> ads_;
    /**
     * <code>repeated .oteldemo.Ad ads = 1;</code>
     */
    @java.lang.Override
    public java.util.List<oteldemo.Demo.Ad> getAdsList() {
      return ads_;
    }
    /**
     * <code>repeated .oteldemo.Ad ads = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends oteldemo.Demo.AdOrBuilder> 
        getAdsOrBuilderList() {
      return ads_;
    }
    /**
     * <code>repeated .oteldemo.Ad ads = 1;</code>
     */
    @java.lang.Override
    public int getAdsCount() {
      return ads_.size();
    }
    /**
     * <code>repeated .oteldemo.Ad ads = 1;</code>
     */
    @java.lang.Override
    public oteldemo.Demo.Ad getAds(int index) {
      return ads_.get(index);
    }
    /**
     * <code>repeated .oteldemo.Ad ads = 1;</code>
     */
    @java.lang.Override
    public oteldemo.Demo.AdOrBuilder getAdsOrBuilder(
        int index) {
      return ads_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < ads_.size(); i++) {
        output.writeMessage(1, ads_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < ads_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, ads_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof oteldemo.Demo.AdResponse)) {
        return super.equals(obj);
      }
      oteldemo.Demo.AdResponse other = (oteldemo.Demo.AdResponse) obj;

      if (!getAdsList()
          .equals(other.getAdsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAdsCount() > 0) {
        hash = (37 * hash) + ADS_FIELD_NUMBER;
        hash = (53 * hash) + getAdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static oteldemo.Demo.AdResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oteldemo.Demo.AdResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oteldemo.Demo.AdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oteldemo.Demo.AdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oteldemo.Demo.AdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oteldemo.Demo.AdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oteldemo.Demo.AdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static oteldemo.Demo.AdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static oteldemo.Demo.AdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static oteldemo.Demo.AdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static oteldemo.Demo.AdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static oteldemo.Demo.AdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(oteldemo.Demo.AdResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code oteldemo.AdResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:oteldemo.AdResponse)
        oteldemo.Demo.AdResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return oteldemo.Demo.internal_static_oteldemo_AdResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return oteldemo.Demo.internal_static_oteldemo_AdResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                oteldemo.Demo.AdResponse.class, oteldemo.Demo.AdResponse.Builder.class);
      }

      // Construct using oteldemo.Demo.AdResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAdsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (adsBuilder_ == null) {
          ads_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          adsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return oteldemo.Demo.internal_static_oteldemo_AdResponse_descriptor;
      }

      @java.lang.Override
      public oteldemo.Demo.AdResponse getDefaultInstanceForType() {
        return oteldemo.Demo.AdResponse.getDefaultInstance();
      }

      @java.lang.Override
      public oteldemo.Demo.AdResponse build() {
        oteldemo.Demo.AdResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public oteldemo.Demo.AdResponse buildPartial() {
        oteldemo.Demo.AdResponse result = new oteldemo.Demo.AdResponse(this);
        int from_bitField0_ = bitField0_;
        if (adsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            ads_ = java.util.Collections.unmodifiableList(ads_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.ads_ = ads_;
        } else {
          result.ads_ = adsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof oteldemo.Demo.AdResponse) {
          return mergeFrom((oteldemo.Demo.AdResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(oteldemo.Demo.AdResponse other) {
        if (other == oteldemo.Demo.AdResponse.getDefaultInstance()) return this;
        if (adsBuilder_ == null) {
          if (!other.ads_.isEmpty()) {
            if (ads_.isEmpty()) {
              ads_ = other.ads_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAdsIsMutable();
              ads_.addAll(other.ads_);
            }
            onChanged();
          }
        } else {
          if (!other.ads_.isEmpty()) {
            if (adsBuilder_.isEmpty()) {
              adsBuilder_.dispose();
              adsBuilder_ = null;
              ads_ = other.ads_;
              bitField0_ = (bitField0_ & ~0x00000001);
              adsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAdsFieldBuilder() : null;
            } else {
              adsBuilder_.addAllMessages(other.ads_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        oteldemo.Demo.AdResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (oteldemo.Demo.AdResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<oteldemo.Demo.Ad> ads_ =
        java.util.Collections.emptyList();
      private void ensureAdsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          ads_ = new java.util.ArrayList<oteldemo.Demo.Ad>(ads_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          oteldemo.Demo.Ad, oteldemo.Demo.Ad.Builder, oteldemo.Demo.AdOrBuilder> adsBuilder_;

      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public java.util.List<oteldemo.Demo.Ad> getAdsList() {
        if (adsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ads_);
        } else {
          return adsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public int getAdsCount() {
        if (adsBuilder_ == null) {
          return ads_.size();
        } else {
          return adsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public oteldemo.Demo.Ad getAds(int index) {
        if (adsBuilder_ == null) {
          return ads_.get(index);
        } else {
          return adsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public Builder setAds(
          int index, oteldemo.Demo.Ad value) {
        if (adsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdsIsMutable();
          ads_.set(index, value);
          onChanged();
        } else {
          adsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public Builder setAds(
          int index, oteldemo.Demo.Ad.Builder builderForValue) {
        if (adsBuilder_ == null) {
          ensureAdsIsMutable();
          ads_.set(index, builderForValue.build());
          onChanged();
        } else {
          adsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public Builder addAds(oteldemo.Demo.Ad value) {
        if (adsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdsIsMutable();
          ads_.add(value);
          onChanged();
        } else {
          adsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public Builder addAds(
          int index, oteldemo.Demo.Ad value) {
        if (adsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAdsIsMutable();
          ads_.add(index, value);
          onChanged();
        } else {
          adsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public Builder addAds(
          oteldemo.Demo.Ad.Builder builderForValue) {
        if (adsBuilder_ == null) {
          ensureAdsIsMutable();
          ads_.add(builderForValue.build());
          onChanged();
        } else {
          adsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public Builder addAds(
          int index, oteldemo.Demo.Ad.Builder builderForValue) {
        if (adsBuilder_ == null) {
          ensureAdsIsMutable();
          ads_.add(index, builderForValue.build());
          onChanged();
        } else {
          adsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public Builder addAllAds(
          java.lang.Iterable<? extends oteldemo.Demo.Ad> values) {
        if (adsBuilder_ == null) {
          ensureAdsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ads_);
          onChanged();
        } else {
          adsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public Builder clearAds() {
        if (adsBuilder_ == null) {
          ads_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          adsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public Builder removeAds(int index) {
        if (adsBuilder_ == null) {
          ensureAdsIsMutable();
          ads_.remove(index);
          onChanged();
        } else {
          adsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public oteldemo.Demo.Ad.Builder getAdsBuilder(
          int index) {
        return getAdsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public oteldemo.Demo.AdOrBuilder getAdsOrBuilder(
          int index) {
        if (adsBuilder_ == null) {
          return ads_.get(index);  } else {
          return adsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public java.util.List<? extends oteldemo.Demo.AdOrBuilder> 
           getAdsOrBuilderList() {
        if (adsBuilder_ != null) {
          return adsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ads_);
        }
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public oteldemo.Demo.Ad.Builder addAdsBuilder() {
        return getAdsFieldBuilder().addBuilder(
            oteldemo.Demo.Ad.getDefaultInstance());
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public oteldemo.Demo.Ad.Builder addAdsBuilder(
          int index) {
        return getAdsFieldBuilder().addBuilder(
            index, oteldemo.Demo.Ad.getDefaultInstance());
      }
      /**
       * <code>repeated .oteldemo.Ad ads = 1;</code>
       */
      public java.util.List<oteldemo.Demo.Ad.Builder> 
           getAdsBuilderList() {
        return getAdsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          oteldemo.Demo.Ad, oteldemo.Demo.Ad.Builder, oteldemo.Demo.AdOrBuilder> 
          getAdsFieldBuilder() {
        if (adsBuilder_ == null) {
          adsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              oteldemo.Demo.Ad, oteldemo.Demo.Ad.Builder, oteldemo.Demo.AdOrBuilder>(
                  ads_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          ads_ = null;
        }
        return adsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:oteldemo.AdResponse)
    }

    // @@protoc_insertion_point(class_scope:oteldemo.AdResponse)
    private static final oteldemo.Demo.AdResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new oteldemo.Demo.AdResponse();
    }

    public static oteldemo.Demo.AdResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AdResponse>
        PARSER = new com.google.protobuf.AbstractParser<AdResponse>() {
      @java.lang.Override
      public AdResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AdResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AdResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public oteldemo.Demo.AdResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:oteldemo.Ad)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * url to redirect to when an ad is clicked.
     * </pre>
     *
     * <code>string redirect_url = 1;</code>
     * @return The redirectUrl.
     */
    java.lang.String getRedirectUrl();
    /**
     * <pre>
     * url to redirect to when an ad is clicked.
     * </pre>
     *
     * <code>string redirect_url = 1;</code>
     * @return The bytes for redirectUrl.
     */
    com.google.protobuf.ByteString
        getRedirectUrlBytes();

    /**
     * <pre>
     * short advertisement text to display.
     * </pre>
     *
     * <code>string text = 2;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <pre>
     * short advertisement text to display.
     * </pre>
     *
     * <code>string text = 2;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code oteldemo.Ad}
   */
  public static final class Ad extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:oteldemo.Ad)
      AdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Ad.newBuilder() to construct.
    private Ad(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ad() {
      redirectUrl_ = "";
      text_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Ad();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Ad(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              redirectUrl_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return oteldemo.Demo.internal_static_oteldemo_Ad_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return oteldemo.Demo.internal_static_oteldemo_Ad_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              oteldemo.Demo.Ad.class, oteldemo.Demo.Ad.Builder.class);
    }

    public static final int REDIRECT_URL_FIELD_NUMBER = 1;
    private volatile java.lang.Object redirectUrl_;
    /**
     * <pre>
     * url to redirect to when an ad is clicked.
     * </pre>
     *
     * <code>string redirect_url = 1;</code>
     * @return The redirectUrl.
     */
    @java.lang.Override
    public java.lang.String getRedirectUrl() {
      java.lang.Object ref = redirectUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        redirectUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * url to redirect to when an ad is clicked.
     * </pre>
     *
     * <code>string redirect_url = 1;</code>
     * @return The bytes for redirectUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRedirectUrlBytes() {
      java.lang.Object ref = redirectUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        redirectUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object text_;
    /**
     * <pre>
     * short advertisement text to display.
     * </pre>
     *
     * <code>string text = 2;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * short advertisement text to display.
     * </pre>
     *
     * <code>string text = 2;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(redirectUrl_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, redirectUrl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(redirectUrl_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, redirectUrl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof oteldemo.Demo.Ad)) {
        return super.equals(obj);
      }
      oteldemo.Demo.Ad other = (oteldemo.Demo.Ad) obj;

      if (!getRedirectUrl()
          .equals(other.getRedirectUrl())) return false;
      if (!getText()
          .equals(other.getText())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REDIRECT_URL_FIELD_NUMBER;
      hash = (53 * hash) + getRedirectUrl().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static oteldemo.Demo.Ad parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oteldemo.Demo.Ad parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oteldemo.Demo.Ad parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oteldemo.Demo.Ad parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oteldemo.Demo.Ad parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static oteldemo.Demo.Ad parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static oteldemo.Demo.Ad parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static oteldemo.Demo.Ad parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static oteldemo.Demo.Ad parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static oteldemo.Demo.Ad parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static oteldemo.Demo.Ad parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static oteldemo.Demo.Ad parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(oteldemo.Demo.Ad prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code oteldemo.Ad}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:oteldemo.Ad)
        oteldemo.Demo.AdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return oteldemo.Demo.internal_static_oteldemo_Ad_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return oteldemo.Demo.internal_static_oteldemo_Ad_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                oteldemo.Demo.Ad.class, oteldemo.Demo.Ad.Builder.class);
      }

      // Construct using oteldemo.Demo.Ad.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        redirectUrl_ = "";

        text_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return oteldemo.Demo.internal_static_oteldemo_Ad_descriptor;
      }

      @java.lang.Override
      public oteldemo.Demo.Ad getDefaultInstanceForType() {
        return oteldemo.Demo.Ad.getDefaultInstance();
      }

      @java.lang.Override
      public oteldemo.Demo.Ad build() {
        oteldemo.Demo.Ad result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public oteldemo.Demo.Ad buildPartial() {
        oteldemo.Demo.Ad result = new oteldemo.Demo.Ad(this);
        result.redirectUrl_ = redirectUrl_;
        result.text_ = text_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof oteldemo.Demo.Ad) {
          return mergeFrom((oteldemo.Demo.Ad)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(oteldemo.Demo.Ad other) {
        if (other == oteldemo.Demo.Ad.getDefaultInstance()) return this;
        if (!other.getRedirectUrl().isEmpty()) {
          redirectUrl_ = other.redirectUrl_;
          onChanged();
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        oteldemo.Demo.Ad parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (oteldemo.Demo.Ad) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object redirectUrl_ = "";
      /**
       * <pre>
       * url to redirect to when an ad is clicked.
       * </pre>
       *
       * <code>string redirect_url = 1;</code>
       * @return The redirectUrl.
       */
      public java.lang.String getRedirectUrl() {
        java.lang.Object ref = redirectUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          redirectUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * url to redirect to when an ad is clicked.
       * </pre>
       *
       * <code>string redirect_url = 1;</code>
       * @return The bytes for redirectUrl.
       */
      public com.google.protobuf.ByteString
          getRedirectUrlBytes() {
        java.lang.Object ref = redirectUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          redirectUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * url to redirect to when an ad is clicked.
       * </pre>
       *
       * <code>string redirect_url = 1;</code>
       * @param value The redirectUrl to set.
       * @return This builder for chaining.
       */
      public Builder setRedirectUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        redirectUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * url to redirect to when an ad is clicked.
       * </pre>
       *
       * <code>string redirect_url = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRedirectUrl() {
        
        redirectUrl_ = getDefaultInstance().getRedirectUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * url to redirect to when an ad is clicked.
       * </pre>
       *
       * <code>string redirect_url = 1;</code>
       * @param value The bytes for redirectUrl to set.
       * @return This builder for chaining.
       */
      public Builder setRedirectUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        redirectUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <pre>
       * short advertisement text to display.
       * </pre>
       *
       * <code>string text = 2;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * short advertisement text to display.
       * </pre>
       *
       * <code>string text = 2;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * short advertisement text to display.
       * </pre>
       *
       * <code>string text = 2;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * short advertisement text to display.
       * </pre>
       *
       * <code>string text = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * short advertisement text to display.
       * </pre>
       *
       * <code>string text = 2;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:oteldemo.Ad)
    }

    // @@protoc_insertion_point(class_scope:oteldemo.Ad)
    private static final oteldemo.Demo.Ad DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new oteldemo.Demo.Ad();
    }

    public static oteldemo.Demo.Ad getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ad>
        PARSER = new com.google.protobuf.AbstractParser<Ad>() {
      @java.lang.Override
      public Ad parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ad(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ad> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ad> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public oteldemo.Demo.Ad getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oteldemo_AdRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oteldemo_AdRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oteldemo_AdResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oteldemo_AdResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oteldemo_Ad_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oteldemo_Ad_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\022\010oteldemo\032\037google/protobuf/" +
      "timestamp.proto\"!\n\tAdRequest\022\024\n\014context_" +
      "keys\030\001 \003(\t\"\'\n\nAdResponse\022\031\n\003ads\030\001 \003(\0132\014." +
      "oteldemo.Ad\"(\n\002Ad\022\024\n\014redirect_url\030\001 \001(\t\022" +
      "\014\n\004text\030\002 \001(\t2B\n\tAdService\0225\n\006GetAds\022\023.o" +
      "teldemo.AdRequest\032\024.oteldemo.AdResponse\"" +
      "\000B\023Z\021genproto/oteldemob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_oteldemo_AdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_oteldemo_AdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oteldemo_AdRequest_descriptor,
        new java.lang.String[] { "ContextKeys", });
    internal_static_oteldemo_AdResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_oteldemo_AdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oteldemo_AdResponse_descriptor,
        new java.lang.String[] { "Ads", });
    internal_static_oteldemo_Ad_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_oteldemo_Ad_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oteldemo_Ad_descriptor,
        new java.lang.String[] { "RedirectUrl", "Text", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
