# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: 1

contactPoints:
  - orgId: 1
    name: grafana-default-email
    receivers:
      - uid: grafana-default-email-uid
        type: email
        settings:
          addresses: admin@example.com

policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by:
      - grafana_folder
      - alertname
