# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: Jaeger
    uid: webstore-traces
    type: jaeger
    url: http://jaeger:16686/jaeger/ui
    editable: true
    isDefault: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: webstore-logs
        spanStartTimeShift: "-20m"
        spanEndTimeShift: "20m"
        filterByTraceID: true
        filterBySpanID: true
        customQuery: true
        query: traceId:"$${__trace.traceId}" AND spanId:"$${__span.spanId}"
