# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: Okapi Metrics
    uid: okapi-metrics
    type: prometheus
    url: ${OKAPI_PROMQL_ENDPOINT}
    editable: true
    isDefault: false
    jsonData:
      timeInterval: "60s"
