# Kubernetes manifest for demo-service-account
# ServiceAccount used by all Astronomy Shop application pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-demo
  labels:
    app.kubernetes.io/version: 2.1.3
    app.kubernetes.io/part-of: opentelemetry-demo
