# Kubernetes manifest for flagd-ui
# Split from combined flagd/flagd-ui deployment
---
apiVersion: v1
kind: Service
metadata:
  name: flagd-ui
  labels:
    opentelemetry.io/name: flagd-ui
    app.kubernetes.io/component: flagd-ui
    app.kubernetes.io/name: flagd-ui
    app.kubernetes.io/version: 2.1.3
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: ClusterIP
  ports:
  - port: 4000
    name: tcp-service
    targetPort: 4000
  selector:
    opentelemetry.io/name: flagd-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd-ui
  labels:
    opentelemetry.io/name: flagd-ui
    app.kubernetes.io/component: flagd-ui
    app.kubernetes.io/name: flagd-ui
    app.kubernetes.io/version: 2.1.3
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      opentelemetry.io/name: flagd-ui
  template:
    metadata:
      labels:
        opentelemetry.io/name: flagd-ui
        app.kubernetes.io/component: flagd-ui
        app.kubernetes.io/name: flagd-ui
    spec:
      serviceAccountName: opentelemetry-demo
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: opentelemetry.io/name
                operator: In
                values:
                - flagd
            topologyKey: kubernetes.io/hostname
      containers:
      - name: flagd-ui
        image: ghcr.io/open-telemetry/demo:2.1.3-flagd-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
          name: service
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_COLLECTOR_NAME
          value: $(NODE_IP)
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_COLLECTOR_NAME):4318
        - name: FLAGD_UI_PORT
          value: '4000'
        - name: SECRET_KEY_BASE
          value: yYrECL4qbNwleYInGJYvVnSkwJuSQJ4ijPTx5tirGUXrbznFIBFVJdPl5t6O9ASw
        - name: PHX_HOST
          value: localhost
        - name: FLAGD_HOST
          value: flagd
        - name: FLAGD_PORT
          value: '8013'
        resources:
          limits:
            memory: 250Mi
        volumeMounts:
        - mountPath: /app/data
          name: config-rw
      initContainers:
      - command:
        - sh
        - -c
        - cp /config-ro/demo.flagd.json /config-rw/demo.flagd.json && cat /config-rw/demo.flagd.json
        image: busybox
        name: init-config
        volumeMounts:
        - mountPath: /config-ro
          name: config-ro
        - mountPath: /config-rw
          name: config-rw
      volumes:
      - name: config-rw
        persistentVolumeClaim:
          claimName: flagd-shared-config
      - configMap:
          name: flagd-config
        name: config-ro
