# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

dirs:
  - .

excludedFiles:
  - ./CHANGELOG.md

ignorePatterns:
  - pattern: "^http://localhost:8080"
  - pattern: "^https://calendar.google.com/calendar"

aliveStatusCodes:
  - 200
  - 429

useGitIgnore: true

modifiedFilesOnly: false
