# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# Need this to avoid getting "bot denied"
user_agent = "Mozilla/5.0 (compatible; lychee link checker)"

max_retries = 3
retry_wait_time = 10
timeout = 30
max_concurrency = 1

exclude = [
  "^http://localhost",
  "^https://calendar\\.google\\.com/calendar",
  "^https://www\\.gnu\\.org",
  "^https://platform\\.openai\\.com",
]

exclude_path = [
  "CHANGELOG\\.md",
]

accept = ["200", "429"]
