# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

networks:
  default:
    name: opentelemetry-demo
    driver: bridge

services:
  otel-ebpf-profiler:
    image: ${COLLECTOR_EBPF_PROFILER_IMAGE}
    container_name: otel-ebpf-profiler
    command:
      - --config=/etc/ebpf-profiler-config.yaml
      - --feature-gates=service.profilesSupport
    privileged: true
    pid: "host"
    environment:
      - OTEL_COLLECTOR_HOST
      - OTEL_COLLECTOR_PORT_GRPC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./src/otel-collector/otelcol-ebpf-profiling.yml:/etc/ebpf-profiler-config.yaml:ro
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/kernel/tracing:/sys/kernel/tracing
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /proc:/proc:ro
    depends_on:
      - otel-collector

  firepit:
    image: ${FIREPIT_IMAGE}
    container_name: firepit
    ports:
      - "${FIREPIT_PORT}"
    environment:
      - BASE_PATH=/profiles
