# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

services:

  ad:
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/9555'"]
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 20

  cart:
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 7070"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 20

  currency:
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 7001"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 20

  email:
    healthcheck:
      test: ["CMD", "ruby", "-e", "require 'socket'; TCPSocket.new('localhost', 6060).close"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 20

  frontend:
    healthcheck:
      test: ["CMD", "/nodejs/bin/node", "-e", "require('http').get('http://frontend:8080/',(r)=>{process.exit(0)}).on('error',()=>process.exit(1))"]
      start_period: 15s
      interval: 5s
      timeout: 5s
      retries: 20

  llm:
    healthcheck:
      test: ["CMD", "python3", "-c", "import socket; s=socket.create_connection(('localhost',8000),2); s.close()"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 20

  payment:
    healthcheck:
      test:
        - "CMD"
        - "/nodejs/bin/node"
        - "-e"
        - >-
          const net=require('net');const c=new net.Socket();
          c.setTimeout(2000);
          c.connect(50051,'127.0.0.1',()=>{c.destroy();process.exit(0)});
          c.on('error',()=>process.exit(1));
          c.on('timeout',()=>process.exit(1))
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 20

  product-reviews:
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3551"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 20

  quote:
    healthcheck:
      test: ["CMD", "php", "-r", "fsockopen('localhost', 8090) or die('fail');"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 20

  recommendation:
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9001"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 20

  postgresql:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10

  valkey-cart:
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping"]
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 10

  otel-collector:
    command: [ "--config=/etc/otelcol-config.yml", "--config=/etc/otelcol-config-tracetest.yml" ]
    environment:
      - ENVOY_PORT
      - OTEL_COLLECTOR_HOST
      - OTEL_COLLECTOR_PORT_GRPC
      - OTEL_COLLECTOR_PORT_HTTP
    volumes:
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
      - ${OTEL_COLLECTOR_CONFIG}:/etc/otelcol-config.yml
      - ./test/tracetesting/otelcol-config-tracetest.yml:/etc/otelcol-config-tracetest.yml
    depends_on: []
