docker push styblope/otel-demo:v1.2.1-accountingservice      
docker push styblope/otel-demo:v1.2.1-frontend              
docker push styblope/otel-demo:v1.2.1-adservice             
docker push styblope/otel-demo:v1.2.1-quoteservice          
docker push styblope/otel-demo:v1.2.1-checkoutservice       
docker push styblope/otel-demo:v1.2.1-productcatalogservice 
docker push styblope/otel-demo:v1.2.1-loadgenerator         
docker push styblope/otel-demo:v1.2.1-cartservice           
docker push styblope/otel-demo:v1.2.1-paymentservice        
docker push styblope/otel-demo:v1.2.1-recommendationservice 
docker push styblope/otel-demo:v1.2.1-shippingservice       
docker push styblope/otel-demo:v1.2.1-kafka                 
docker push styblope/otel-demo:v1.2.1-currencyservice       
docker push styblope/otel-demo:v1.2.1-featureflagservice    
docker push styblope/otel-demo:v1.2.1-frauddetectionservice 
docker push styblope/otel-demo:v1.2.1-emailservice          
docker push styblope/otel-demo:v1.2.1-frontendproxy         
