k8s_yaml(helm('../opentelemetry-helm-charts/charts/opentelemetry-demo/', values=['./values.yaml']))
k8s_resource(workload='chart-frontendproxy', port_forwards=8080)

docker_build('demo:local-adservice', context='./', dockerfile='./src/adservice/Dockerfile')
docker_build('demo:local-accountingservice',context='./', dockerfile='./src/accountingservice/Dockerfile')
docker_build('demo:local-cartservice',context='./', dockerfile='./src/cartservice/src/Dockerfile')
docker_build('demo:local-checkoutservice',context='./', dockerfile='./src/checkoutservice/Dockerfile')
docker_build('demo:local-currencyservice',context='./src/currencyservice', dockerfile='./src/currencyservice/Dockerfile')
docker_build('demo:local-emailservice',context='./src/emailservice', dockerfile='./src/emailservice/Dockerfile')
docker_build('demo:local-featureflagservice',context='./', dockerfile='./src/featureflagservice/Dockerfile')
docker_build('demo:local-frauddetectionservice',context='./', dockerfile='./src/frauddetectionservice/Dockerfile')
docker_build('demo:local-loadgenerator',context='./', dockerfile='./src/loadgenerator/Dockerfile')
docker_build('demo:local-paymentservice',context='./', dockerfile='./src/paymentservice/Dockerfile')
docker_build('demo:local-productcatalogservice',context='./', dockerfile='./src/productcatalogservice/Dockerfile')
docker_build('demo:local-recommendationservice',context='./', dockerfile='./src/recommendationservice/Dockerfile')
docker_build('demo:local-shippingservice',context='./', dockerfile='./src/shippingservice/Dockerfile')
docker_build('demo:local-frontend',context='./', dockerfile='./src/frontend/Dockerfile')
docker_build('demo:local-frontendproxy',context='./', dockerfile='./src/frontendproxy/Dockerfile')
docker_build('demo:local-quoteservice',context='./', dockerfile='./src/quoteservice/Dockerfile')
docker_build('demo:local-kafka',context='./', dockerfile='./src/kafka/Dockerfile')
