

source "https://rubygems.org"

gem "net-smtp", "~> 0.5.1"
gem "pony",     "~> 1.13"
gem "puma",     "~> 6.6"
gem "sinatra",  "~> 4.1"
gem "rackup",   "~> 2.2"

gem "google-protobuf", "~> 4.31.1"

gem "opentelemetry-sdk",                 "~> 1.8"
gem "opentelemetry-exporter-otlp",       "~> 0.30.0"
gem "opentelemetry-instrumentation-all", "~> 0.76.0"
