# =============================================================================
# OpenTelemetry Demo - Azure Infrastructure
# =============================================================================
#
# This Terraform configuration deploys the following Azure resources:
# - Azure Data Explorer (ADX) cluster with database and tables
# - Azure Kubernetes Service (AKS) cluster with Workload Identity enabled
# - User-Assigned Managed Identity with Federated Credential
# - Virtual Network for AKS
#
# =============================================================================


# =============================================================================
# Resource Group
# =============================================================================

resource "azurerm_resource_group" "main" {
  name     = "${local.resource_prefix}-rg"
  location = var.location

  tags = local.common_tags
}

# =============================================================================
# Virtual Network (Optional - for private AKS)
# =============================================================================

resource "azurerm_virtual_network" "main" {
  name                = "${local.resource_prefix}-vnet"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  address_space       = var.vnet_address_space

  tags = local.common_tags
}

resource "azurerm_subnet" "aks" {
  name                 = "aks-subnet"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = [var.aks_subnet_address_prefix]
}

# =============================================================================
# Azure Data Explorer Module
# =============================================================================

module "adx" {
  source = "./modules/adx"

  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  cluster_name        = "${replace(local.resource_prefix, "-", "")}adx"
  database_name       = var.adx_database_name

  sku_name          = var.adx_sku_name
  sku_capacity      = var.adx_sku_capacity
  hot_cache_days    = var.adx_hot_cache_days
  retention_days    = var.adx_retention_days
  auto_stop_enabled = var.adx_auto_stop_enabled

  tags = local.common_tags
}

# =============================================================================
# Azure Kubernetes Service Module
# =============================================================================

module "aks" {
  source = "./modules/aks"

  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  cluster_name        = "${local.resource_prefix}-aks"

  kubernetes_version            = var.aks_kubernetes_version
  default_node_pool_vm_size     = var.aks_default_node_pool_vm_size
  default_node_pool_count       = var.aks_default_node_pool_count
  default_node_pool_min_count   = var.aks_default_node_pool_min_count
  default_node_pool_max_count   = var.aks_default_node_pool_max_count
  enable_auto_scaling           = var.aks_enable_auto_scaling
  subnet_id                     = azurerm_subnet.aks.id

  tags = local.common_tags
}

# =============================================================================
# Workload Identity Module (for ADX authentication)
# Uses User-Assigned Managed Identity with Federated Credential
# =============================================================================

module "identity" {
  source = "./modules/identity"

  identity_name        = "${local.resource_prefix}-otel-collector-identity"
  resource_group_name  = azurerm_resource_group.main.name
  location             = azurerm_resource_group.main.location
  oidc_issuer_url      = module.aks.oidc_issuer_url
  namespace            = "otel-demo"
  service_account_name = "otel-collector-sa"
  adx_cluster_id       = module.adx.cluster_id
  adx_database_name    = module.adx.database_name

  tags = local.common_tags

  depends_on = [module.adx, module.aks]
}

# =============================================================================
# Generate Helm Values File for Azure Deployment (Workload Identity)
# =============================================================================

resource "local_file" "helm_values" {
  filename = "${path.module}/../kubernetes/opentelemetry-demo-chart/values-generated.yaml"
  content  = <<-EOT
    # Copyright The OpenTelemetry Authors
    # SPDX-License-Identifier: Apache-2.0
    #
    # Generated by Terraform - DO NOT EDIT MANUALLY
    # Re-run 'terraform apply' to regenerate this file
    #
    # Usage:
    #   helm install otel-demo ./kubernetes/opentelemetry-demo-chart \
    #     -f ./kubernetes/opentelemetry-demo-chart/values-generated.yaml
    #

    namespace: otel-demo

    # Azure Data Explorer Configuration
    adx:
      enabled: true
      clusterUri: "${module.adx.cluster_uri}"
      database: "${module.adx.database_name}"
      tables:
        traces: "OTelTraces"
        metrics: "OTelMetrics"
        logs: "OTelLogs"
      mappings:
        traces: "otel_traces_mapping"
        metrics: "otel_metrics_mapping"
        logs: "otel_logs_mapping"
      ingestionType: "managed"

    # Azure Workload Identity Configuration (No secrets needed!)
    azure:
      workloadIdentity:
        enabled: true
        clientId: "${module.identity.client_id}"
      tenantId: "${module.identity.tenant_id}"

    # Grafana Configuration
    grafana:
      enabled: true
      adminUser: admin
      adminPassword: admin
      plugins: grafana-azure-data-explorer-datasource
      # ADX Service Principal for Grafana datasource
      # (ADX plugin v7.2.1 doesn't support Workload Identity)
      adxDatasource:
        clientId: "${module.identity.grafana_adx_client_id}"
        clientSecret: "${module.identity.grafana_adx_client_secret}"

    # OpenTelemetry Collector Configuration
    otelCollector:
      enabled: true
      version: "0.135.0"
      serviceAccount:
        name: "otel-collector-sa"
        annotations:
          azure.workload.identity/client-id: "${module.identity.client_id}"
      healthCheck:
        enabled: true
        port: 13133
      queue:
        enabled: true
        numConsumers: 10
        queueSize: 5000
      retry:
        enabled: true
        initialInterval: 5s
        maxInterval: 30s
        maxElapsedTime: 300s
  EOT

  depends_on = [module.identity, module.adx]
}

# =============================================================================
# Generate Kubeconfig
# =============================================================================

resource "local_file" "kubeconfig" {
  filename        = "${path.module}/kubeconfig"
  content         = module.aks.kube_config_raw
  file_permission = "0600"
}
