# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# =============================================================================
# OpenTelemetry Demo - Azure Infrastructure
# =============================================================================
#
# This Terraform configuration deploys the following Azure resources:
# - Azure Data Explorer (ADX) cluster with database and tables
# - Azure Kubernetes Service (AKS) cluster
# - Service Principal for ADX authentication
# - Virtual Network for AKS (optional)
#
# =============================================================================

# =============================================================================
# Local Variables
# =============================================================================

locals {
  resource_prefix = "${var.project_name}-${var.environment}"

  common_tags = merge(var.tags, {
    Environment = var.environment
    Project     = var.project_name
  })
}

# =============================================================================
# Resource Group
# =============================================================================

resource "azurerm_resource_group" "main" {
  name     = "${local.resource_prefix}-rg"
  location = var.location

  tags = local.common_tags
}

# =============================================================================
# Virtual Network (Optional - for private AKS)
# =============================================================================

resource "azurerm_virtual_network" "main" {
  name                = "${local.resource_prefix}-vnet"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  address_space       = var.vnet_address_space

  tags = local.common_tags
}

resource "azurerm_subnet" "aks" {
  name                 = "aks-subnet"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = [var.aks_subnet_address_prefix]
}

# =============================================================================
# Azure Data Explorer Module
# =============================================================================

module "adx" {
  source = "./modules/adx"

  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  cluster_name        = "${replace(local.resource_prefix, "-", "")}adx"
  database_name       = var.adx_database_name

  sku_name          = var.adx_sku_name
  sku_capacity      = var.adx_sku_capacity
  hot_cache_days    = var.adx_hot_cache_days
  retention_days    = var.adx_retention_days
  auto_stop_enabled = var.adx_auto_stop_enabled

  tags = local.common_tags
}

# =============================================================================
# Azure Kubernetes Service Module
# =============================================================================

module "aks" {
  source = "./modules/aks"

  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  cluster_name        = "${local.resource_prefix}-aks"

  kubernetes_version            = var.aks_kubernetes_version
  default_node_pool_vm_size     = var.aks_default_node_pool_vm_size
  default_node_pool_count       = var.aks_default_node_pool_count
  default_node_pool_min_count   = var.aks_default_node_pool_min_count
  default_node_pool_max_count   = var.aks_default_node_pool_max_count
  enable_auto_scaling           = var.aks_enable_auto_scaling
  subnet_id                     = azurerm_subnet.aks.id

  tags = local.common_tags
}

# =============================================================================
# Service Principal Module (for ADX authentication)
# =============================================================================

module "identity" {
  source = "./modules/identity"

  application_name       = "${local.resource_prefix}-otel-collector"
  password_rotation_days = var.sp_password_rotation_days
  adx_cluster_id         = module.adx.cluster_id
  adx_database_name      = module.adx.database_name

  tags = local.common_tags

  depends_on = [module.adx]
}

# =============================================================================
# Generate Kubernetes Secret YAML
# =============================================================================

resource "local_file" "k8s_secret" {
  filename = "${path.module}/../kubernetes/azure/secrets.yaml"
  content  = <<-EOT
    # Copyright The OpenTelemetry Authors
    # SPDX-License-Identifier: Apache-2.0
    #
    # Generated by Terraform - DO NOT EDIT MANUALLY
    # Re-run 'terraform apply' to regenerate this file
    #
    apiVersion: v1
    kind: Secret
    metadata:
      name: adx-credentials
      namespace: otel-demo
      labels:
        app.kubernetes.io/name: adx-credentials
        app.kubernetes.io/part-of: opentelemetry-demo
    type: Opaque
    stringData:
      AZURE_TENANT_ID: "${module.identity.tenant_id}"
      AZURE_CLIENT_ID: "${module.identity.client_id}"
      AZURE_CLIENT_SECRET: "${module.identity.client_secret}"
      ADX_CLUSTER_URI: "${module.adx.cluster_uri}"
      ADX_INGESTION_URI: "${module.adx.cluster_data_ingestion_uri}"
      ADX_DATABASE: "${module.adx.database_name}"
  EOT

  depends_on = [module.identity, module.adx]
}

# =============================================================================
# Generate Helm Values File for Azure Deployment
# =============================================================================

resource "local_file" "helm_values" {
  filename = "${path.module}/../kubernetes/opentelemetry-demo-chart/values-generated.yaml"
  content  = <<-EOT
    # Copyright The OpenTelemetry Authors
    # SPDX-License-Identifier: Apache-2.0
    #
    # Generated by Terraform - DO NOT EDIT MANUALLY
    # Re-run 'terraform apply' to regenerate this file
    #
    # Usage:
    #   helm install otel-demo ./kubernetes/opentelemetry-demo-chart \
    #     -f ./kubernetes/opentelemetry-demo-chart/values-generated.yaml
    #

    namespace: otel-demo

    # Azure Data Explorer Configuration
    adx:
      enabled: true
      clusterUri: "${module.adx.cluster_uri}"
      database: "${module.adx.database_name}"
      tables:
        traces: "OTelTraces"
        metrics: "OTelMetrics"
        logs: "OTelLogs"
      mappings:
        traces: "otel_traces_mapping"
        metrics: "otel_metrics_mapping"
        logs: "otel_logs_mapping"
      ingestionType: "managed"

    # Azure Authentication
    azure:
      tenantId: "${module.identity.tenant_id}"
      clientId: "${module.identity.client_id}"
      clientSecret: "${module.identity.client_secret}"
      existingSecret: ""

    # Grafana Configuration
    grafana:
      enabled: true
      adminUser: admin
      adminPassword: admin
      plugins: grafana-azure-data-explorer-datasource

    # OpenTelemetry Collector Configuration
    otelCollector:
      enabled: true
      version: "0.135.0"
      healthCheck:
        enabled: true
        port: 13133
      queue:
        enabled: true
        numConsumers: 10
        queueSize: 5000
      retry:
        enabled: true
        initialInterval: 5s
        maxInterval: 30s
        maxElapsedTime: 300s
  EOT

  depends_on = [module.identity, module.adx]
}

# =============================================================================
# Generate Kubeconfig
# =============================================================================

resource "local_file" "kubeconfig" {
  filename        = "${path.module}/kubeconfig"
  content         = module.aks.kube_config_raw
  file_permission = "0600"
}
