opentelemetry-collector:
  mode: "daemonset"
  presets:
    kubernetesAttributes:
      enabled: true
    kubeletMetrics:
      enabled: true
    hostMetrics:
      enabled: true
    logsCollection:
      enabled: true
      includeCollectorLogs: false
      storeCheckpoints: true
