{
 "title": "Delivery Metrics Demo Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "organization",
    "label": "organization",
    "query": {
     "query": "label_values(organization_name)"
    }
   },
   {
    "name": "team",
    "label": "team",
    "query": {
     "query": "label_values({organization_name=\"$organization\"},team_name)"
    }
   },
   {
    "name": "repo",
    "query": {
     "query": "label_values({organization_name=~\"$organization\"}, repository_name) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Branch Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(organization_name) (git_repository_branch_count{organization_name=\"$organization\", repository_name=~\"$repo\"})",
     "legendFormat": "{{organization_name}}"
    }
   ]
  },
  {
   "title": "Average Branch Age Per Repo In Days",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(repository_name) (git_repository_branch_time{organization_name=\"$organization\", repository_name=~\"$repo\"}) / 24",
     "legendFormat": "{{repository_name}}"
    }
   ]
  },
  {
   "title": "Contributor Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "git_repository_contributor_count{organization_name=\"$organization\", repository_name=~\"$repo\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}"
    }
   ]
  },
  {
   "title": "Branch Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "git_repository_branch_count{organization_name=\"$organization\", repository_name=~\"$repo\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}"
    }
   ]
  },
  {
   "title": "Branch Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "git_repository_branch_time{organization_name=\"$organization\", repository_name=~\"$repo\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Open Pull Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "git_repository_pull_request_open_count{organization_name=\"$organization\", repository_name=~\"$repo\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Open Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "git_repository_pull_request_open_time{organization_name=\"$organization\", repository_name=~\"$repo\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Repo Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "git_repository_count{organization_name=\"$organization\"}",
     "legendFormat": "{{organization_name}}"
    }
   ]
  },
  {
   "title": "Merged Pull Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "git_repository_pull_request_merged_count{organization_name=\"$organization\", repository_name=~\"$repo\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Merged Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "git_repository_pull_request_merged_time{organization_name=\"$organization\", repository_name=~\"$repo\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  },
  {
   "title": "Approved Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "git_repository_pull_request_approved_time{organization_name=\"$organization\", repository_name=~\"$repo\"}",
     "legendFormat": "{{organization_name}}/{{repository_name}}/{{branch_name}}"
    }
   ]
  }
 ]
}