{
 "title": "[Image-Provider] NGINX Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Accepted connections",
   "type": "stat",
   "description": "The total number of accepted client connections",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"nginx.connections_accepted\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections handled",
   "type": "stat",
   "description": "The total number of handled connections",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"nginx.connections_handled\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total number of client requests",
   "type": "stat",
   "description": "The total number of client requests",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"nginx.requests\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of connections by state",
   "type": "timeseries",
   "description": "The current number of nginx connections by state",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{\"nginx.connections.current\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}