apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opentelemetry-demo-grafana
  namespace: otel-demo
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/version: "11.3.0"
rules: []