# Kubernetes manifest for astronomy-loadgen
# Includes scriptfile ConfigMap used by the deployment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scriptfile
data:
  local-file: |
    /* eslint-disable no-console */
    const { Console } = require('console');
    const puppeteer = require('puppeteer');
    const customUserAgent = 'Mozilla/5.0 (X11; Linux x86_64; Splunk RUM_LoadGen) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36';
    console.log('DEBUG: Using User Agent:', customUserAgent);

    // Global browser instance for reuse across cycles
    let globalBrowser = null;

    async function launchBrowser() {
      console.log('🔹 Starting headless browser...');
      const browser = await puppeteer.launch({
        headless: true,
        defaultViewport: null,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-gpu',
          '--disable-dev-shm-usage',
          '--disable-web-security',
          '--disable-features=VizDisplayCompositor',
          '--max-old-space-size=256',
          '--disable-extensions',
          '--disable-plugins',
          '--disable-background-networking',
          '--disable-background-timer-throttling',
          '--disable-backgrounding-occluded-windows',
          '--disable-renderer-backgrounding',
          '--memory-pressure-off',
          '--aggressive-cache-discard',
          `--user-agent=${customUserAgent}`
        ]
      });
      console.log('✅ Browser started.');
      return browser;
    }

    async function ensureBrowser() {
      if (!globalBrowser || !globalBrowser.isConnected()) {
        console.log('🔄 Launching new global browser instance...');
        globalBrowser = await launchBrowser();
      }
      return globalBrowser;
    }

    function buildBaseUrl() {
      const raw = (process.env.RUM_FRONTEND_IP || '').trim();

      // If it's empty, default to localhost
      if (!raw) return 'https://localhost/';

      // If it already starts with http:// or https://, keep it exactly as-is
      if (/^https?:\/\//i.test(raw)) {
        return raw.replace(/\/+$/, '') + '/';
      }

      // Otherwise, prepend https://
      return `https://${raw.replace(/\/+$/, '')}/`;
    }

    function getProductIds() {
      const envProductIds = (process.env.PRODUCT_IDS || '').trim();
      if (envProductIds) {
        return envProductIds.split(',').map(id => id.trim()).filter(id => id);
      }
      // Hardcoded product IDs if env variable is not set or empty
      return [
        'OLJCESPC7Z', // National Park Foundation Explorascope
        '66VCHSJNUP', // Starsense Explorer Refractor Telescope
        '1YMWWN1N4O', // Eclipsmart Travel Refractor Telescope
        'L9ECAV7KIM', // Lens Cleaning Kit
        '2ZYFJ3GM2N', // Roof Binoculars
        '0PUK6V6EV0', // Solar System Color Imager
        'LS4PSXUNUM', // Red Flashlight
        '9SIQT8TOJO', // Optical Tube Assembly
        '6E92ZMYYFZ', // Solar Filter
        'HQTGWGPNH4'  // The Comet Book
      ];
    }

    function getRandomProducts() {
      const allProducts = getProductIds();
      const numProducts = Math.floor(Math.random() * 3) + 1; // Random number between 1 and 3
      const shuffled = allProducts.sort(() => Math.random() - 0.5);
      return shuffled.slice(0, numProducts);
    }

    function delay(ms) { return new Promise(res => setTimeout(res, ms)); }

    /** Wait until innerText of the page contains a substring */
    async function waitForText(page, text, timeoutMs = 30000, pollMs = 200) {
      const start = Date.now();
      while (Date.now() - start < timeoutMs) {
        const found = await page.evaluate(t =>
          document && document.body && document.body.innerText.includes(t),
          text
        );
        if (found) return true;
        await delay(pollMs);
      }
      throw new Error(`Timed out waiting for text: "${text}"`);
    }

    async function runOnce() {
      const browser = await ensureBrowser();
      let page;
      try {
        page = await browser.newPage();
        page.setDefaultNavigationTimeout(45000);
        page.setDefaultTimeout && page.setDefaultTimeout(30000);

        const base = buildBaseUrl();
        const productsToOrder = getRandomProducts();
        console.log(`🛒 Ordering ${productsToOrder.length} product(s): ${productsToOrder.join(', ')}`);

        // Loop through each product and add to cart
        for (const productId of productsToOrder) {
          const url = new URL(`product/${productId}`, base).toString();
          console.log(`🌐 Navigating to ${url}`);
          await page.goto(url, { waitUntil: 'domcontentloaded' });

          console.log('🖱️ Clicking quick prompts...');

          // Click "Can you summarize the product reviews?"
          {
              console.log('🔍 Examining product reviews...');
              const targetPage = page;
              const timeout = 5000;
              await puppeteer.Locator.race([
                  targetPage.locator('::-p-aria(Can you summarize the product reviews?)'),
                  targetPage.locator("[data-cy='QuickPromptSummarize']"),
                  targetPage.locator('::-p-xpath(//*[@data-cy=\\"QuickPromptSummarize\\"])'),
                  targetPage.locator(":scope >>> [data-cy='QuickPromptSummarize']"),
                  targetPage.locator('::-p-text(Can you summarize)')
              ])
                  .setTimeout(timeout)
                  .click({
                    offset: {
                      x: 129,
                      y: 15,
                    },
                  });
              console.log('⏳ Waiting for AI response...');
              await delay(500); // Let request start
              await page.waitForSelector("[data-cy='AIAnswer']", { timeout: 15000, visible: true }).catch(() => {
                console.log('⚠️ AI response timeout, continuing...');
              });
              await delay(1500); // Allow response to fully render
          }

          // Click "Were there any negative reviews?"
          {
              const targetPage = page;
              const timeout = 5000;
              await puppeteer.Locator.race([
                  targetPage.locator('::-p-aria(Were there any negative reviews?)'),
                  targetPage.locator("[data-cy='QuickPromptNegative']"),
                  targetPage.locator('::-p-xpath(//*[@data-cy=\\"QuickPromptNegative\\"])'),
                  targetPage.locator(":scope >>> [data-cy='QuickPromptNegative']"),
                  targetPage.locator('::-p-text(Were there any)')
              ])
                  .setTimeout(timeout)
                  .click({
                    offset: {
                      x: 171.6640625,
                      y: 25,
                    },
                  });
              console.log('⏳ Waiting for AI response...');
              await delay(500); // Let request start
              await page.waitForSelector("[data-cy='AIAnswer']", { timeout: 15000, visible: true }).catch(() => {
                console.log('⚠️ AI response timeout, continuing...');
              });
              await delay(1500); // Allow response to fully render
          }

          // Click "What age(s) is this recommended for?"
          {
              const targetPage = page;
              const timeout = 5000;
              await puppeteer.Locator.race([
                  targetPage.locator('::-p-aria(What age\\(s\\) is this recommended for?)'),
                  targetPage.locator("[data-cy='QuickPromptAges']"),
                  targetPage.locator('::-p-xpath(//*[@data-cy=\\"QuickPromptAges\\"])'),
                  targetPage.locator(":scope >>> [data-cy='QuickPromptAges']"),
                  targetPage.locator('::-p-text(What age\\(s\\) is)')
              ])
                  .setTimeout(timeout)
                  .click({
                    offset: {
                      x: 148.0390625,
                      y: 19,
                    },
                  });
              console.log('⏳ Waiting for AI response...');
              await delay(500); // Let request start
              await page.waitForSelector("[data-cy='AIAnswer']", { timeout: 15000, visible: true }).catch(() => {
                console.log('⚠️ AI response timeout, continuing...');
              });
              await delay(1500); // Allow response to fully render
          }

          const addSel = "[data-cy='product-add-to-cart']";
          await page.waitForSelector(addSel);
          console.log(`🖱️ Clicking "Add To Cart" for product ${productId}`);
          await page.click(addSel);
        }

        // Place order after all products are added to cart
        const placeSel = "[data-cy='checkout-place-order']";
        await page.waitForSelector(placeSel);
        console.log('🖱️ Clicking "Place Order"');
        await page.click(placeSel);

        await waitForText(page, 'Your order is complete!');
        console.log('🎉 Order completed message detected.');
      } finally {
        console.log('🧹 Cleaning up page resources...');
        try {
          if (page) {
            page.removeAllListeners();
            await page.close({ runBeforeUnload: true }).catch(()=>{});
          }
        } catch (e) {
          console.error('⚠️ Error closing page:', e.message);
        }
        console.log('✅ Page closed cleanly. Browser will be reused for next cycle.');
      }
    }

    (async function mainLoop() {
      const cycleDelayMs = parseInt(process.env.CYCLE_DELAY_MS || '5000', 10);
      console.log(`⚙️ Cycle delay: ${cycleDelayMs}ms`);

      let cycle = 1;
      while (true) {
        console.log(`=== Starting load generation cycle #${cycle} ===`);
        try {
          await runOnce();
          console.log(`✅ Cycle #${cycle} finished OK`);
        } catch (e) {
          console.error(`❌ Cycle #${cycle} failed:`, e && e.stack ? e.stack : e);
        }
        cycle += 1;
        await delay(cycleDelayMs);
      }
    })();
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: astronomy-loadgen-deployment
  labels:
    app: astronomy-loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astronomy-loadgen
  template:
    metadata:
      labels:
        app: astronomy-loadgen
    spec:
      containers:
      - name: astronomy-loadgen
        image: ghcr.io/splunk/online-boutique/rumloadgen:5.6
        imagePullPolicy: Always
        env:
        - name: RUM_FRONTEND_IP
          value: "http://frontend-proxy:8080"
        - name: CYCLE_DELAY_MS
          value: "1000"
        volumeMounts:
        - name: puppeteer
          subPath: local-file
          mountPath: /puppeteer/touchwebsite.js
      volumes:
      - name: puppeteer
        configMap:
          name: scriptfile
