---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
    component: otel-demo-currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
      component: otel-demo-currencyservice
  template:
    metadata:
      labels:
        service: currencyservice
        app: currencyservice
        component: otel-demo-currencyservice
    spec:
      containers:
        - name: currencyservice
          image: otel/demo:${DOCKER_IMAGE_VERSION}-currencyservice
          imagePullPolicy: Always
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
            requests:
              memory: 200Mi
              cpu: 100m
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: OTEL_RESOURCE
              value: k8s.pod.ip=$(MY_POD_IP)
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_AGENT_ENDPOINT
              value: "$(HOST_IP)"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(OTEL_AGENT_ENDPOINT):4318"
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://$(OTEL_AGENT_ENDPOINT):4317"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=currencyservice,
              deployment.environment=staging"
            - name: APP_ENV
              value: staging
            - name: PORT
              value: "7000"
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  labels:
    app: currencyservice
    component: otel-demo-currencyservice
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 7000
      protocol: TCP
      name: http
  selector:
    app: currencyservice
    component: otel-demo-currencyservice
---
