### Expects a deployment of Astronomy Shop Demo in the same cluster
### Uses checkout service from that demo
### Or add this at config at the end of an astronomy shop demo deployment yaml
---
apiVersion: v1
kind: Service
metadata:
  name: shop-dc-shim-db
  namespace: default
  labels:
    opentelemetry.io/name: shop-dc-shim-db
    app.kubernetes.io/component: shop-dc-shim-db
    app.kubernetes.io/name: shop-dc-shim-db
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: ClusterIP
  ports:
    - port: 1433
      name: sqlserver
      targetPort: 1433
  selector:
    opentelemetry.io/name: shop-dc-shim-db
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: shop-dc-shim-db
  namespace: default
  labels:
    opentelemetry.io/name: shop-dc-shim-db
    app.kubernetes.io/component: shop-dc-shim-db
    app.kubernetes.io/name: shop-dc-shim-db
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      opentelemetry.io/name: shop-dc-shim-db
  template:
    metadata:
      labels:
        opentelemetry.io/name: shop-dc-shim-db
        app.kubernetes.io/component: shop-dc-shim-db
        app.kubernetes.io/name: shop-dc-shim-db
        app.kubernetes.io/version: "2.1.3"
        app.kubernetes.io/part-of: opentelemetry-demo
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "ShopPass123!"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "2"
          volumeMounts:
            - name: sqlserver-storage
              mountPath: /var/opt/mssql/data
      volumes:
        - name: sqlserver-storage
          emptyDir: {}