// Code generated by OpenFeature CLI. DO NOT EDIT.
// CLI version: dev

// Package flags contains generated code produced by the OpenFeature CLI.
package flags

import (
	"context"
	"fmt"

	"github.com/open-feature/go-sdk/openfeature"
)

// stringer transforms a string to a Stringer
type stringer string

// String implements the fmt.Stringer interface
func (s stringer) String() string {
	return string(s)
}

type (
	evaluationValue[T any]   func(context.Context, openfeature.EvaluationContext) T
	evaluationDetails[T any] func(context.Context, openfeature.EvaluationContext) (openfeature.GenericEvaluationDetails[T], error)
)

var client = openfeature.NewDefaultClient()

// KafkaQueueProblems returns the value of the "kafkaQueueProblems" feature flag.
// simulates kafka queue problems
//
// The flag is a type of integer and defaults to 0.
var KafkaQueueProblems = struct {
	fmt.Stringer
	// Value returns the value of the [KafkaQueueProblems] flag.
	Value evaluationValue[int64]

	// ValueWithDetails returns the evaluation details of the [KafkaQueueProblems] flag
	// and the evaluation error, if any.
	ValueWithDetails evaluationDetails[int64]
}{
	Stringer: stringer("kafkaQueueProblems"),
	Value: func(ctx context.Context, evalCtx openfeature.EvaluationContext) int64 {
		return client.Int(ctx, "kafkaQueueProblems", 0, evalCtx)
	},
	ValueWithDetails: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.GenericEvaluationDetails[int64], error) {
		return client.IntValueDetails(ctx, "kafkaQueueProblems", 0, evalCtx)
	},
}

// PaymentUnreachable returns the value of the "paymentUnreachable" feature flag.
// simulates payment unreachable issue
//
// The flag is a type of boolean and defaults to false.
var PaymentUnreachable = struct {
	fmt.Stringer
	// Value returns the value of the [PaymentUnreachable] flag.
	Value evaluationValue[bool]

	// ValueWithDetails returns the evaluation details of the [PaymentUnreachable] flag
	// and the evaluation error, if any.
	ValueWithDetails evaluationDetails[bool]
}{
	Stringer: stringer("paymentUnreachable"),
	Value: func(ctx context.Context, evalCtx openfeature.EvaluationContext) bool {
		return client.Boolean(ctx, "paymentUnreachable", false, evalCtx)
	},
	ValueWithDetails: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.GenericEvaluationDetails[bool], error) {
		return client.BooleanValueDetails(ctx, "paymentUnreachable", false, evalCtx)
	},
}
