// Code generated by OpenFeature CLI. DO NOT EDIT.
// CLI version: dev

// Package flags contains generated code produced by the OpenFeature CLI.
package flags

import (
	"context"
	"fmt"

	"github.com/open-feature/go-sdk/openfeature"
)

// stringer transforms a string to a Stringer
type stringer string

// String implements the fmt.Stringer interface
func (s stringer) String() string {
	return string(s)
}

type (
	evaluationValue[T any]   func(context.Context, openfeature.EvaluationContext) T
	evaluationDetails[T any] func(context.Context, openfeature.EvaluationContext) (openfeature.GenericEvaluationDetails[T], error)
)

var client = openfeature.NewDefaultClient()

// ProductCatalogFailure returns the value of the "productCatalogFailure" feature flag.
// simulates a potential product catalog failure scenario
//
// The flag is a type of boolean and defaults to false.
var ProductCatalogFailure = struct {
	fmt.Stringer
	// Value returns the value of the [ProductCatalogFailure] flag.
	Value evaluationValue[bool]

	// ValueWithDetails returns the evaluation details of the [ProductCatalogFailure] flag
	// and the evaluation error, if any.
	ValueWithDetails evaluationDetails[bool]
}{
	Stringer: stringer("productCatalogFailure"),
	Value: func(ctx context.Context, evalCtx openfeature.EvaluationContext) bool {
		return client.Boolean(ctx, "productCatalogFailure", false, evalCtx)
	},
	ValueWithDetails: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.GenericEvaluationDetails[bool], error) {
		return client.BooleanValueDetails(ctx, "productCatalogFailure", false, evalCtx)
	},
}

// ProductCatalogLockContention returns the value of the "productCatalogLockContention" feature flag.
// simulates lock contention on the product catalog database
//
// The flag is a type of boolean and defaults to false.
var ProductCatalogLockContention = struct {
	fmt.Stringer
	// Value returns the value of the [ProductCatalogLockContention] flag.
	Value evaluationValue[bool]

	// ValueWithDetails returns the evaluation details of the [ProductCatalogLockContention] flag
	// and the evaluation error, if any.
	ValueWithDetails evaluationDetails[bool]
}{
	Stringer: stringer("productCatalogLockContention"),
	Value: func(ctx context.Context, evalCtx openfeature.EvaluationContext) bool {
		return client.Boolean(ctx, "productCatalogLockContention", false, evalCtx)
	},
	ValueWithDetails: func(ctx context.Context, evalCtx openfeature.EvaluationContext) (openfeature.GenericEvaluationDetails[bool], error) {
		return client.BooleanValueDetails(ctx, "productCatalogLockContention", false, evalCtx)
	},
}
