### Expects a deployment of Astronomy Shop Demo in the same cluster
### Uses checkout service from that demo
### Or add this at config at the end of an astronomy shop demo deployment yaml
---
# Shop DC Shim Service
apiVersion: v1
kind: Service
metadata:
  name: shop-dc-shim
  namespace: default
  labels:
    opentelemetry.io/name: shop-dc-shim
    app.kubernetes.io/component: shop-dc-shim
    app.kubernetes.io/name: shop-dc-shim
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: ClusterIP
  ports:
    - port: 8070
      name: tcp-service
      targetPort: 8070
  selector:
    opentelemetry.io/name: shop-dc-shim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-dc-shim
  namespace: default
  labels:
    opentelemetry.io/name: shop-dc-shim
    app.kubernetes.io/component: shop-dc-shim
    app.kubernetes.io/name: shop-dc-shim
    app.kubernetes.io/version: "2.1.3"
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      opentelemetry.io/name: shop-dc-shim
  template:
    metadata:
      labels:
        opentelemetry.io/name: shop-dc-shim
        app.kubernetes.io/component: shop-dc-shim
        app.kubernetes.io/name: shop-dc-shim
        app.kubernetes.io/version: "2.1.3"
        app.kubernetes.io/part-of: opentelemetry-demo
    spec:
      serviceAccountName: opentelemetry-demo
      containers:
        - name: shop-dc-shim
          image: ghcr.io/splunk/opentelemetry-demo/otel-shop-dc-shim:1.4.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8070
              name: http
          command: ["/usr/bin/dumb-init"]
          args:
          - --
          - /bin/bash
          - -c
          - |
            export OTEL_RESOURCE_ATTRIBUTES="service.name=shop-dc-shim-service,deployment.environment=${ENV_VALUE}-datacenter-b01,service.version=2.1.3,service.namespace=shop-dc-shim"
            exec /app/start-app-dual.sh    
          env:
            - name: WORKSHOP_ENV
              valueFrom:
                secretKeyRef:
                  name: workshop-secret
                  key: env
            - name: SHOP_DC_SHIM_PORT
              value: "8070"
            - name: DB_CONNECTION_STRING
              value: "jdbc:sqlserver://shop-dc-shim-db:1433;databaseName=master;encrypt=false;trustServerCertificate=true"
            - name: DB_USERNAME
              value: "sa"
            - name: DB_PASSWORD
              value: "ShopPass123!"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkout:8080"
            - name: EMAIL_SERVICE_URL
              value: "http://email:8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://splunk-otel-collector-agent:4318"
            - name: OTEL_SERVICE_NAME
              value: "shop-dc-shim"
            - name: OTEL_JAVAAGENT_ENABLED
              value: "true"
            - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
              value: "se-lab"
            - name: APPDYNAMICS_JAVAAGENT_ENABLED
              value: "true"
            - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: workshop-secret
                  key: appd_token
            - name: OTEL_INSTRUMENTATION_SPLUNK_JDBC_ENABLED
              value: "true"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8070
            initialDelaySeconds: 240
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8070
            initialDelaySeconds: 420
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5