# frozen_string_literal: true

source 'https://rubygems.org'

gem 'net-smtp',                              '~> 0.3'
gem 'opentelemetry-exporter-otlp',           '~> 0.24'
gem 'opentelemetry-instrumentation-sinatra', '~> 0.22'
gem 'opentelemetry-sdk',                     '~> 1.2'
gem 'pony',                                  '~> 1.13'
gem 'puma',                                  '~> 6.2'
gem 'sinatra',                               '~> 3.0'
