source "https://rubygems.org"

gem "net-smtp", "~> 0.3"
gem "pony",     "~> 1.13"
gem "puma",     "~> 5.6"
gem "sinatra",  "~> 2.2"

gem "opentelemetry-sdk",                     "~> 1.1"
gem "opentelemetry-exporter-otlp",           "~> 0.21"
gem "opentelemetry-instrumentation-sinatra", "~> 0.19"
