# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

file_format: definition/2
attributes:
  - key: product.id
    type: string
    brief: Product identifier
    stability: stable
    examples: ["66VCHSJNUP", "OLJCESPC7Z"]
    note: The unique identifier of the product

metrics:
  - name: app_product_review_counter
    brief: Product review counter
    instrument: counter
    unit: "{review_request}"
    stability: stable
    annotations:
      service: product_reviews
    attributes:
      - ref: product.id
        requirement_level: required
        note: The unique identifier of the product for which reviews are being retrieved

  - name: app_ai_assistant_counter
    brief: AI assistant request counter
    instrument: counter
    unit: "{ai_request}"
    stability: stable
    annotations:
      service: product_reviews
    attributes:
      - ref: product.id
        requirement_level: required
        note: The unique identifier of the product for which AI assistance is being requested
