# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: product-store
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "host=product_db user=postgres password=example port=5432 connect_timeout=10 database=postgres"
    - name: tableName
      value: productstate
    - name: cleanupInterval
      value: 0
