# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# assigns reviewers to pull requests in a similar way as CODEOWNERS, but doesn't require reviewers
# to have write access to the repository
# see .github/component_owners.yaml for the list of components and their owners
name: Assign reviewers

on:
  # pull_request_target is needed instead of just pull_request
  # because repository write permission is needed to assign reviewers
  pull_request_target:

permissions:
  contents: read

jobs:
  assign-reviewers:
    permissions:
      pull-requests: write  # required for assigning reviewers to PRs
    if: github.repository == 'open-telemetry/opentelemetry-demo'
    runs-on: ubuntu-latest
    steps:
      - uses: dyladan/component-owners@main
        with:
          # using this action to request review only (not assignment)
          assign-owners: false
