# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Test image generation

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'

permissions:
  contents: read

jobs:
  build_images:
    name: Build images
    permissions:
      contents: read  # required by the component-build-images reusable workflow
      packages: write  # required to push built images to GHCR
    if: ${{ !github.event.repository.fork }}
    uses: ./.github/workflows/component-build-images.yml
