# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Test image generation

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_images:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/component-build-images.yml
