
name: 'Cleanup GHCR Images'

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  cleanup_ghcr_images:
    runs-on: ubuntu-latest
  
    steps:
      - name: Delete GHCR Unwanted Images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'opentelemetry-demo'
          package-type: 'container'
          # Set to 0 because keeping a fixed count of images is unreliable.
          # We protect important release images strictly by their tags in ignore-versions below.
          min-versions-to-keep: 0
          ignore-versions: |
            latest
            ^v[0-9]+.*
        


