# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: FOSSA scanning

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98  # v5.0.1

      - uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3  # v1.9.0
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          team: OpenTelemetry
