# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: FOSSA scanning

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  fossa:
    name: FOSSA scan
    if: ${{ !github.event.repository.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124  # v1.24.1
        with:
          otp-version: "28.4"
          elixir-version: "1.20.1"
          version-type: strict

      - name: Run FOSSA scan
        uses: fossas/fossa-action@29693cc50323968e039056be419b32989fc5880c  # v2.0.0
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          team: OpenTelemetry
