# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Gradle wrapper validation
on:
  pull_request:
    paths:
      - '**/gradle/wrapper/**'
  push:
    paths:
      - '**/gradle/wrapper/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  validation:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92  # v6.2.0
