# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: "Build and Publish"

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build_and_push_images:
    permissions:  # required by the reusable workflow
      contents: read  # required by the component-build-images reusable workflow
      packages: write  # required to push built images to GHCR
    uses: ./.github/workflows/component-build-images.yml
    if: ${{ !github.event.repository.fork }}
    with:
      push: true
      version: ${{ github.event.release.tag_name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
