# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Integration Tests

on:
  pull_request_review:
    types:
      - submitted

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: "Run CI"
    if: github.event.review.state == 'APPROVED'
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false
      - name: Run tracetesting
        run: |
          make build && docker system prune -f && make run-tracetesting
