# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: zizmor scan

on:
  workflow_call:

permissions: {}

concurrency:
  group: zizmor-workflow-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

env:
  FORCE_COLOR: 3
  TERM: xterm

jobs:
  zizmor:
    name: Scan with zizmor
    runs-on: ubuntu-24.04
    permissions:
      actions: read  # required to scan GitHub Actions workflows
      contents: read  # required to checkout the repository
      security-events: write  # required to upload zizmor SARIF to code scanning
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          filter: "tree:0"
          persist-credentials: false
          show-progress: false

      - name: Scan workflows with zizmor
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02  # v0.6.0
        with:
          persona: pedantic
