exporters:
  otlp_grpc/mybackend:
    endpoint: http://host.docker.internal:4317
    headers:
      x-api-key: "9b7610fa"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      exporters: [spanmetrics, otlp_grpc/jaeger, otlp_grpc/mybackend]
    metrics:
      exporters: [otlp_http/prometheus, otlp_grpc/mybackend]
    logs:
      exporters: [otlp_grpc/mybackend]